version: 2

seeds:
  - name: RAW_TAXI_ZONES
    description: "Raw data for taxi zones."
    config:
      column_types:
        LocationID: NUMBER(4)
        Borough: VARCHAR2(50)
        Zone: VARCHAR2(50)
        service_zone: VARCHAR2(50)
      docs:
        node_color: "#FF5733"
    columns:
      - name: LocationID
        data_tests:
          - unique
          - not_null
      - name: Borough
        data_tests:
          - not_null
      - name: Zone
        data_tests:
          - not_null
      - name: service_zone
        data_tests:
          - not_null
  - name: DIM_YELLOW_TAXI
    description: "Dimension table for yellow taxi zones."
    config:
      column_types:
        FIELD: VARCHAR2(50)
        CODE: NUMBER(4)
        VALUE: VARCHAR2(50)
      docs:
        node_color: "#33FF57"
  - name: DIM_GREEN_TAXI
    description: "Dimension table for yellow taxi zones."
    config:
      column_types:
        FIELD: VARCHAR2(50)
        CODE: NUMBER(4)
        VALUE: VARCHAR2(50)
      docs:
        node_color: "#33FF57"
