
version: 2

sources:
  - name: pdave
    tables:
      - name: RAW_YELLOW_TRIPDATA
        columns:
          - name: VENDORID
            description: 'TPEP provider code.'
          - name: TPEP_PICKUP_DATETIME
            description: 'Pickup date and time.'
          - name: TPEP_DROPOFF_DATETIME
            description: 'Dropoff date and time.'
          - name: PASSENGER_COUNT
            description: 'Number of passengers.'
          - name: TRIP_DISTANCE
            description: 'Trip distance in miles.'
          - name: RATECODEID
            description: 'Rate code at trip end.'
          - name: STORE_AND_FWD_FLAG
            description: 'Indicates if trip data was stored.'
          - name: PULOCATIONID
            description: 'Pickup location zone.'
          - name: DOLOCATIONID
            description: 'Dropoff location zone.'
          - name: PAYMENT_TYPE
            description: 'Payment method code.'
          - name: FARE_AMOUNT
            description: 'Time and distance fare.'
          - name: EXTRA
            description: 'Miscellaneous extras and surcharges.'
          - name: MTA_TAX
            description: 'MTA tax amount.'
          - name: TIP_AMOUNT
            description: 'Credit card tip amount.'
          - name: TOLLS_AMOUNT
            description: 'Total toll amount.'
          - name: IMPROVEMENT_SURCHARGE
            description: 'Improvement surcharge amount.'
          - name: TOTAL_AMOUNT
            description: 'Total amount charged.'
          - name: CONGESTION_SURCHARGE
            description: 'Congestion surcharge amount.'
          - name: AIRPORT_FEE
            description: 'Airport fee for pickups.'
      - name: RAW_GREEN_TRIPDATA
      - name: RAW_FHV_TRIPDATA
        columns:
          - name: PULOCATIONID
            description: 'Pickup location zone.'
            data_tests:
              - not_null:
                  config:
                    severity: warn
          - name: DOLOCATIONID
            description: 'Dropoff location zone.'

      - name: RAW_HVFHV_TRIPDATA


models:
  - name: dim_calendar
    description: "A calendar dimension table"
  - name: stg_green_taxi
    description: "Cleaned green taxi data"
    columns:
      - name: vendor_id
        description: 'TPEP provider code.'
      - name: pickup_datetime
        description: 'Pickup date and time.'
      - name: dropoff_datetime
        description: 'Dropoff date and time.'
      - name: passenger_count
        description: 'Number of passengers.'
      - name: trip_distance
        description: 'Trip distance in miles.'
      - name: rate_code_id
        description: 'Rate code at trip end.'
      - name: store_and_fwd_flag
        description: 'Indicates if trip data was stored.'
      - name: pickup_location_id
        description: 'Pickup location zone.'
      - name: dropoff_location_id
        description: 'Dropoff location zone.'
      - name: payment_type
        description: 'Payment method code.'
      - name: fare_amount
        description: 'Time and distance fare.'
      - name: extra
        description: 'Miscellaneous extras and surcharges.'
      - name: mta_tax
        description: 'MTA tax amount.'
      - name: tip_amount
        description: 'Credit card tip amount.'
      - name: tolls_amount
        description: 'Total toll amount.'
      - name: improvement_surcharge
        description: 'Improvement surcharge amount.'
      - name: total_amount
        description: 'Total amount charged.'
      - name: congestion_surcharge
        description: 'Congestion surcharge amount.'
      - name: email_fee
        description: 'Email fee amount.'
      - name: trip_type
        description: 'Trip type code.'
  - name: stg_yellow_taxi
    description: "Cleaned yellow taxi data"
    columns:
      - name: vendor_id
        description: 'TPEP provider code.'
      - name: pickup_datetime
        description: 'Pickup date and time.'
      - name: dropoff_datetime
        description: 'Dropoff date and time.'
      - name: passenger_count
        description: 'Number of passengers.'
      - name: trip_distance
        description: 'Trip distance in miles.'
      - name: rate_code_id
        description: 'Rate code at trip end.'
      - name: store_and_fwd_flag
        description: 'Indicates if trip data was stored.'
      - name: pickup_location_id
        description: 'Pickup location zone.'
      - name: dropoff_location_id
        description: 'Dropoff location zone.'
      - name: payment_type
        description: 'Payment method code.'
      - name: fare_amount
        description: 'Time and distance fare.'
      - name: extra
        description: 'Miscellaneous extras and surcharges.'
      - name: mta_tax
        description: 'MTA tax amount.'
      - name: tip_amount
        description: 'Credit card tip amount.'
      - name: tolls_amount
        description: 'Total toll amount.'
      - name: improvement_surcharge
        description: 'Improvement surcharge amount.'
      - name: total_amount
        description: 'Total amount charged.'
      - name: congestion_surcharge
        description: 'Congestion surcharge amount.'
      - name: airport_fee
        description: 'Airport fee for pickups.'
  - name: mart_taxi_tripdata
    description: "Taxi trip data aggregated by month."
    config:
      contract:
        enforced: true
    columns:
      - name: trip_id
        description: 'Unique identifier for each trip.'
        data_type: string
        data_tests:
          - not_null
          - unique
        constraints:
          - type: primary_key
      - name: trip_month
        description: 'Month in YYYY-MM format.'
        data_type: string
      - name: total_trips
        description: 'Total number of trips in the month.'
        data_type: number
      - name: total_passengers
        description: 'Total number of passengers in the month.'
        data_type: number
      - name: total_trip_distance
        description: 'Total trip distance in miles for the month.'
        data_type: number
      - name: total_fare_amount
        description: 'Total fare amount in the month.'
        data_type: number
      - name: total_tip_amount
        description: 'Total tip amount in the month.'
        data_type: number
      - name: total_revenue
        description: 'Total revenue in the month.'
        data_type: number
      - name: taxi_type
        description: 'Type of taxi (green or yellow).'
        data_type: string
      - name: refresh_date
        description: 'Timestamp when the data was last refreshed.'
        data_type: timestamp

  - name: dbt_run_results
    description: "Table to store dbt run results."